### ISSUE TITLE
In `Mapping#should_set_facls?` Replace `owned?` with a FACL Check

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/shiny_admin#24]
Neither `Pathname#owned?` nor `Pathname#writable?` is a sufficient check on whether or not FACLs can be set. Write an explicit check for the existence of FACL attribute `C` and replace the `owned?` check with that.

**Comment by ericfranz** [comment]
This is a great idea. In fact, if the dataset is a “managed dataset” and doesn’t have the C attr set, and corresponding app doesn’t have the C attr set, we should never create the mapping nor attempt the facl modification. This check could be done as a form validation as well.

**Comment by ericfranz** [comment]
In regards to the convention:

The convention we were starting with is that files/datasets are owned by the group, group ownership on files is enforced by sticky bit on directories and proper umask when creating new files and directories. The nice thing about this approach is that it works where facls do not, and so it is a great default approach to handling collaboration on datasets between multiple users in the same group.

However, as we have seen, using this convention doesn't enable users to modify the FACLs of the files and directories. These actions can only be done by the owner of the files/directories, unless the ACL for the GROUP principle includes C **or** an a separate ACL for that user's group (in this case PAS1203) exists in the FACL that has "C".

Test on webtest04, at least with files in the home directory,  setting inheritance works so that files and directories created under `~/awesim/share` and `~/datasets` get "C" for the GROUP principle when this ACL is set on the directory: `A:fdng:GROUP@:rxtncCy` or in the case of the shared apps directory, where working with directories is the only thing that matters: `A:dng:GROUP@:rwaDxtTnNcCy`.

For the admin user I did add this to the bashrc:

```
-bash-4.1$ whoami
bmiadmin
-bash-4.1$ cat ~/.bashrc
# default permissions to 770 for directories and 660 for files
umask 007
```

To experiment, I also set this facl on these two directories: `A:fdng:PAS1203@osc.edu:rwaDxtTnNcCy` and `A:dng:PAS1203@osc.edu:rwaDxtTnNcCy`. I notice that when I do a git clone with the default git version 1.7.1 the umask is ignored for the group, but not for the user so the cloned repos are `drwxr-s---` but these have inherited the ACLs desired: `A:g:GROUP@:rxtncCy` and `A:g:PAS1203@osc.edu:rwaDxtTnNcCy`. But using the scl git 1.9.4 this is fixed: `drwxrws---`.


Also https://www.osc.edu/resources/technical_support/known_issues/aces_of_a_file_in_users_home_directory_will_be_lost_using

So maybe for the bmiadmin user I can add the appropriate `.vimrc` and `cp alias` to avoid issues with vim and cp.


As for having an explicit group principle on each directory and dataset managed vs GROUP, technically it is redundant (since all the files and directories are already owned by the users/groups) but as long as inheritance is working I don't see it hurting anything right now.

**Comment by MorganRodgers** [comment]
Added in #26
